version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:5000"
    environment:
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data: