services:
  - name: ntu-add-drop-app
    type: web
    runtime: docker
    repo: https://github.com/josshhz11/ntu-add-drop-automator
    branch: main
    envVars:
      - key: FLASK_SECRET_KEY
        value: "e9f42fdb2426869b845cc609d4ae9399775cd592b87b0c862e2cc535d5499187"
      - key: REDIS_HOST
        value: "redis"  # Matches the Redis service name in render.yaml
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        generateValue: true  # Auto-generate a secure password
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"
    plan: free
    autoDeploy: true
    env: docker
    region: singapore

  - name: redis  # Add Redis Service
    type: redis
    plan: free  # Use free plan